type Recipe {
  id: ID!
  author: User! @goField(forceResolver: true)
  createdAt: Time!

  currentVersion: RecipeVersion! @goField(forceResolver: true)
  versions: [RecipeVersion!]! @goField(forceResolver: true)

  version(version: Int!): RecipeVersion
}

type RecipeVersion {
  id: ID!
  recipe: Recipe! @goField(forceResolver: true)

  version: Int!
  name: String!
  ingredientUsages: [IngredientUsage!]! @goField(forceResolver: true)
  prepMins: Int!
  cookMins: Int!
  portions: Int!
  source: RecipeSource! @goField(forceResolver: true)

  createdAt: Time!
}

type IngredientUsage {
  id: ID!
  ingredient: Ingredient!
  unit: Unit!
  quantity: Float!
}

type Unit {
  val: Int!
  name: String!
  symbol: String!
}

type RecipeSource {
  type: Int!
  url: String
  bookTitle: String
  bookPage: Int
  instructions: String
}

extend type Query {
  recipes(
    pagination: PaginationInput
    filter: RecipeFilterInput
  ): RecipeConnection!
  recipe(id: ID!): Recipe
}

type RecipeConnection {
  edges: [RecipeEdge!]!
  pageInfo: PageInfo!
  totalCount: Int
}

type RecipeEdge {
  node: Recipe!
  cursor: String!
}

input RecipeFilterInput {
  query: String
}

input CreateRecipeInput {
  name: String!
  ingredientUsages: [CreateIngredientUsageInput!]!
  prepMins: Int!
  cookMins: Int!
  portions: Int!
  recipeSource: CreateRecipeSourceInput!
}

input CreateIngredientUsageInput {
  ingredientID: ID!
  unit: Int!
  quantity: Float!
}

input CreateRecipeSourceInput {
  type: Int!
  url: String
  bookTitle: String
  bookPage: Int
  instructions: String
}

input UpdateRecipeInput {
  id: ID!
  details: CreateRecipeInput!
}

extend type Mutation {
  createRecipe(input: CreateRecipeInput!): Recipe! @auth
  updateRecipe(input: UpdateRecipeInput!): Recipe! @auth
}

