type Recipe {
  id: ID!
  name: String!
  ingredientUsages: [IngredientUsage!]! @goField(forceResolver: true)
  user: User! @goField(forceResolver: true)
  prepMins: Int!
  cookMins: Int!
  portions: Int!
  source: RecipeSource! @goField(forceResolver: true)
}

type IngredientUsage {
  id: ID!
  ingredient: Ingredient!
  unit: Unit!
  quantity: Float!
}

type Unit {
  val: Int!
  name: String!
  symbol: String!
}

type RecipeSource {
  type: Int!
  url: String
  bookTitle: String
  bookPage: Int
  instructions: String
}

extend type Query {
  recipes: [Recipe!]!
  recipe(id: ID!): Recipe
  myRecipes: [Recipe!]! @auth
  myDeletedRecipes: [Recipe!]! @auth
}

input CreateRecipeInput {
  name: String!
  ingredientUsages: [CreateIngredientUsageInput!]!
  prepMins: Int!
  cookMins: Int!
  portions: Int!
  recipeSource: CreateRecipeSourceInput!
}

input CreateIngredientUsageInput {
  ingredientID: ID!
  unit: Int!
  quantity: Float!
}

input CreateRecipeSourceInput {
  type: Int!
  url: String
  bookTitle: String
  bookPage: Int
  instructions: String
}

extend type Mutation {
  createRecipe(input: CreateRecipeInput!): Recipe! @auth
  deleteRecipe(input: DeleteRecipeInput!): Recipe! @auth
  undeleteRecipe(id: ID!): Recipe! @auth
}

input DeleteRecipeInput {
  id: ID!
}