package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"foodplanner/internal/gql/graph/model"
	"net/http"
	"time"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignUpInput) (*model.AuthPayload, error) {
	ip, err := GetIPAddress(ctx)
	if err != nil {
		return nil, err
	}
	user, token, refreshToken, err := r.AuthService.SignUp(input.Email, input.Password, input.Username, ip, ctx)
	if err != nil {
		return nil, err
	}

	w := GetResponseWriter(ctx)
	if w != nil {
		http.SetCookie(w, &http.Cookie{
			Name:     "refreshToken",
			Value:    refreshToken.Token,
			MaxAge:   int(refreshToken.ExpiresAt - time.Now().Unix()),
			Path:     "/",
			HttpOnly: true,
			Secure:   false, // make sure to set this to true in production
			SameSite: http.SameSiteLaxMode,
		})
	}

	return &model.AuthPayload{
		User: mapUser(user),
		Jwt:  token,
	}, nil
}

// Signin is the resolver for the signin field.
func (r *mutationResolver) Signin(ctx context.Context, input model.SignInInput) (*model.AuthPayload, error) {
	ip, err := GetIPAddress(ctx)
	if err != nil {
		return nil, err
	}
	user, token, refreshToken, err := r.AuthService.SignIn(input.Email, input.Password, ip, ctx)
	if err != nil {
		return nil, err
	}

	w := GetResponseWriter(ctx)
	if w != nil {
		http.SetCookie(w, &http.Cookie{
			Name:     "refreshToken",
			Value:    refreshToken.Token,
			MaxAge:   int(refreshToken.ExpiresAt - time.Now().Unix()),
			Path:     "/",
			HttpOnly: true,
			Secure:   false, // make sure to set this to true in production
			SameSite: http.SameSiteLaxMode,
		})
	}

	return &model.AuthPayload{
		User: mapUser(user),
		Jwt:  token,
	}, nil
}
