package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	stderrors "errors"
	"fmt"
	refreshtokens "foodplanner/internal/auth/refresh_tokens"
	grapherrors "foodplanner/internal/gql/graph/errors"
	"foodplanner/internal/gql/graph/model"
	"net/http"
	"time"
)

// Signup is the resolver for the signup field.
func (r *mutationResolver) Signup(ctx context.Context, input model.SignUpInput) (*model.AuthPayload, error) {
	ip, err := GetIPAddress(ctx)
	if err != nil {
		return nil, err
	}
	user, token, refreshToken, err := r.AuthService.SignUp(input.Email, input.Password, input.Username, ip, ctx)
	if err != nil {
		return nil, err
	}

	setRefreshTokenCookie(GetResponseWriter(ctx), refreshToken.Token, refreshToken.ExpiresAt)

	return &model.AuthPayload{
		User: mapUser(user),
		Jwt:  token,
	}, nil
}

// Signin is the resolver for the signin field.
func (r *mutationResolver) Signin(ctx context.Context, input model.SignInInput) (*model.AuthPayload, error) {
	ip, err := GetIPAddress(ctx)
	if err != nil {
		return nil, err
	}
	user, token, refreshToken, err := r.AuthService.SignIn(input.Email, input.Password, ip, ctx)
	if err != nil {
		return nil, err
	}

	setRefreshTokenCookie(GetResponseWriter(ctx), refreshToken.Token, refreshToken.ExpiresAt)

	return &model.AuthPayload{
		User: mapUser(user),
		Jwt:  token,
	}, nil
}

// Refresh is the resolver for the refresh field.
func (r *mutationResolver) Refresh(ctx context.Context) (*model.AuthPayload, error) {
	req := GetRequest(ctx)
	if req == nil {
		return nil, fmt.Errorf("no request in context")
	}
	w := GetResponseWriter(ctx)

	cookie, err := req.Cookie(refreshTokenCookieName)
	if err != nil {
		if err == http.ErrNoCookie {
			clearRefreshTokenCookie(w)
			return nil, grapherrors.NewUnauthenticatedError("No auth cookie found")
		}
		return nil, fmt.Errorf("refresh token cookie not found: %w", err)
	}

	if cookie.Value == "" {
		clearRefreshTokenCookie(w)
		return nil, grapherrors.NewUnauthenticatedError("Empty refresh token")
	}

	ip, err := GetIPAddress(ctx)
	if err != nil {
		return nil, err
	}

	user, jwt, refreshToken, err := r.AuthService.Refresh(ctx, cookie.Value, ip)
	if err != nil {
		if stderrors.Is(err, refreshtokens.ErrInvalidRefreshToken) {
			clearRefreshTokenCookie(w)
			return nil, grapherrors.NewUnauthenticatedError("Invalid refresh token")
		}

		return nil, err
	}

	setRefreshTokenCookie(w, refreshToken.Token, refreshToken.ExpiresAt)

	return &model.AuthPayload{
		User: mapUser(user),
		Jwt:  jwt,
	}, nil
}

func setRefreshTokenCookie(w http.ResponseWriter, token string, expiresAt int64) {
	if w == nil {
		return
	}

	maxAge := int(expiresAt - time.Now().Unix())
	if maxAge < 0 {
		maxAge = 0
	}

	http.SetCookie(w, &http.Cookie{
		Name:     refreshTokenCookieName,
		Value:    token,
		MaxAge:   maxAge,
		Path:     "/",
		HttpOnly: true,
		Secure:   false, // make sure to set this to true in production
		SameSite: http.SameSiteLaxMode,
	})
}

func clearRefreshTokenCookie(w http.ResponseWriter) {
	if w == nil {
		return
	}

	http.SetCookie(w, &http.Cookie{
		Name:     refreshTokenCookieName,
		Value:    "",
		MaxAge:   -1,
		Expires:  time.Unix(0, 0),
		Path:     "/",
		HttpOnly: true,
		Secure:   false, // make sure to set this to true in production
		SameSite: http.SameSiteLaxMode,
	})
}
