package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/logging"
)

// Ingredients is the resolver for the ingredients field.
func (r *queryResolver) Ingredients(ctx context.Context) ([]*model.Ingredient, error) {
	logger := logging.FromContext(ctx)
	ingredients, err := r.IngredientsService.GetAllIngredients(ctx, logger)
	if err != nil {
		logger.Error("Failed to fetch ingredients", "error", err)
		return nil, err
	}
	var ingredientModels []*model.Ingredient
	for _, ingredient := range ingredients {
		ingredientModel := model.Ingredient{
			ID:            ingredient.ID.String(),
			Name:          ingredient.Name,
			PreferredUnit: &model.Unit{Val: int32(ingredient.PreferredUnit), Name: ingredient.PreferredUnit.String(), Symbol: ingredient.PreferredUnit.Symbol()},
		}
		ingredientModels = append(ingredientModels, &ingredientModel)
	}
	return ingredientModels, nil
}
