package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"foodplanner/internal/auth"
	"foodplanner/internal/gql/graph"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/logging"
	"foodplanner/internal/recipe"
)

// CreateRecipe is the resolver for the createRecipe field.
func (r *mutationResolver) CreateRecipe(ctx context.Context, input model.CreateRecipeInput) (*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	claims, err := auth.ClaimsFromContext(ctx)
	if err != nil {
		return nil, err
	}

	ingredientUsageRequests := make([]recipe.CreateIngredientUsageRequest, len(input.IngredientUsages))
	for i, usage := range input.IngredientUsages {
		ingredientUsageRequests[i] = recipe.CreateIngredientUsageRequest{
			IngredientID: usage.IngredientID,
			Quantity:     usage.Quantity,
			Unit:         int(usage.Unit),
		}
	}

	recipeSourceRequest := recipe.CreateRecipeSourceRequest{
		Type:         int(input.RecipeSource.Type),
		URL:          input.RecipeSource.URL,
		BookTitle:    input.RecipeSource.BookTitle,
		BookPage:     input.RecipeSource.BookPage,
		Instructions: input.RecipeSource.Instructions,
	}

	request := recipe.CreateRecipeRequest{
		Name:        input.Name,
		Ingredients: ingredientUsageRequests,
		UserID:      claims.UserID,
		PrepMins:    int(input.PrepMins),
		CookMins:    int(input.CookMins),
		Portions:    int(input.Portions),
		Source:      recipeSourceRequest,
	}
	recipe, err := r.RecipeService.CreateRecipe(ctx, request)
	if err != nil {
		logger.Error("Failed to create recipe", "error", err)
		return nil, err
	}
	recipeModel := &model.Recipe{
		ID:       recipe.ID.String(),
		Name:     recipe.Name,
		PrepMins: int32(recipe.PrepMins),
		CookMins: int32(recipe.CookMins),
		Portions: int32(recipe.Portions),
	}
	return recipeModel, nil
}

// DeleteRecipe is the resolver for the deleteRecipe field.
func (r *mutationResolver) DeleteRecipe(ctx context.Context, input model.DeleteRecipeInput) (*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	claims, err := auth.ClaimsFromContext(ctx)
	if err != nil {
		return nil, err
	}

	recipe, err := r.RecipeService.DeleteRecipe(ctx, input.ID, claims.UserID)
	if err != nil {
		logger.Error("Failed to delete recipe", "error", err)
		return nil, err
	}
	recipeModel := &model.Recipe{
		ID:       recipe.ID.String(),
		Name:     recipe.Name,
		PrepMins: int32(recipe.PrepMins),
		CookMins: int32(recipe.CookMins),
		Portions: int32(recipe.Portions),
	}
	return recipeModel, nil
}

// UndeleteRecipe is the resolver for the undeleteRecipe field.
func (r *mutationResolver) UndeleteRecipe(ctx context.Context, id string) (*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	claims, err := auth.ClaimsFromContext(ctx)
	if err != nil {
		return nil, err
	}

	recipe, err := r.RecipeService.UndeleteRecipe(ctx, id, claims.UserID)
	if err != nil {
		logger.Error("Failed to undelete recipe", "error", err)
		return nil, err
	}
	recipeModel := &model.Recipe{
		ID:       recipe.ID.String(),
		Name:     recipe.Name,
		PrepMins: int32(recipe.PrepMins),
		CookMins: int32(recipe.CookMins),
		Portions: int32(recipe.Portions),
	}
	return recipeModel, nil
}

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context) ([]*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	recipes, err := r.RecipeService.GetAllRecipes(ctx)
	if err != nil {
		logger.Error("Failed to get all recipes", "error", err)
		return nil, err
	}
	var recipeModels []*model.Recipe
	for _, recipe := range recipes {
		recipeModel := model.Recipe{
			ID:       recipe.ID.String(),
			Name:     recipe.Name,
			PrepMins: int32(recipe.PrepMins),
			CookMins: int32(recipe.CookMins),
			Portions: int32(recipe.Portions),
		}
		recipeModels = append(recipeModels, &recipeModel)
	}
	return recipeModels, nil
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id string) (*model.Recipe, error) {
	logger := logging.FromContext(ctx).With("recipe_id", id)
	recipe, err := r.RecipeService.GetRecipeByID(ctx, id)
	if err != nil {
		logger.Error("Failed to get recipe by ID", "error", err)
		return nil, err
	}
	if recipe == nil {
		return nil, nil
	}
	recipeModel := &model.Recipe{
		ID:       recipe.ID.String(),
		Name:     recipe.Name,
		PrepMins: int32(recipe.PrepMins),
		CookMins: int32(recipe.CookMins),
		Portions: int32(recipe.Portions),
	}
	return recipeModel, nil
}

// MyRecipes is the resolver for the myRecipes field.
func (r *queryResolver) MyRecipes(ctx context.Context) ([]*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	claims, err := auth.ClaimsFromContext(ctx)
	if err != nil {
		return nil, err
	}
	recipes, err := r.RecipeService.GetRecipesByUserID(ctx, claims.UserID)
	if err != nil {
		logger.Error("Failed to get recipes for user", "error", err)
		return nil, err
	}
	var recipeModels []*model.Recipe
	for _, recipe := range recipes {
		recipeModel := model.Recipe{
			ID:       recipe.ID.String(),
			Name:     recipe.Name,
			PrepMins: int32(recipe.PrepMins),
			CookMins: int32(recipe.CookMins),
			Portions: int32(recipe.Portions),
		}
		recipeModels = append(recipeModels, &recipeModel)
	}
	return recipeModels, nil
}

// MyDeletedRecipes is the resolver for the myDeletedRecipes field.
func (r *queryResolver) MyDeletedRecipes(ctx context.Context) ([]*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	claims, err := auth.ClaimsFromContext(ctx)
	if err != nil {
		return nil, err
	}
	recipes, err := r.RecipeService.GetDeletedRecipesByUserID(ctx, claims.UserID)
	if err != nil {
		logger.Error("Failed to get deleted recipes for user", "error", err)
		return nil, err
	}
	var recipeModels []*model.Recipe
	for _, recipe := range recipes {
		recipeModel := model.Recipe{
			ID:       recipe.ID.String(),
			Name:     recipe.Name,
			PrepMins: int32(recipe.PrepMins),
			CookMins: int32(recipe.CookMins),
			Portions: int32(recipe.Portions),
		}
		recipeModels = append(recipeModels, &recipeModel)
	}
	return recipeModels, nil
}

// IngredientUsages is the resolver for the ingredientUsages field.
func (r *recipeResolver) IngredientUsages(ctx context.Context, obj *model.Recipe) ([]*model.IngredientUsage, error) {
	logger := logging.FromContext(ctx).With("recipe_id", obj.ID)
	ingredientUsages, err := r.RecipeService.GetIngredientUsagesByRecipeID(ctx, obj.ID)
	if err != nil {
		logger.Error("Failed to get ingredient usages for recipe", "error", err)
		return nil, err
	}

	ingredientIDs := make([]string, len(ingredientUsages))
	for i, usage := range ingredientUsages {
		ingredientIDs[i] = usage.IngredientID.String()
	}

	// Eagerly load ingredients, separate into data loader later
	ingredients, err := r.IngredientsService.GetIngredientsByIDs(ctx, logger, ingredientIDs)
	if err != nil {
		logger.Error("Failed to get ingredients for ingredient usages", "error", err)
		return nil, err
	}
	ingredientMap := make(map[string]*model.Ingredient)
	for _, ingredient := range ingredients {
		ingredientMap[ingredient.ID.String()] = &model.Ingredient{
			ID:   ingredient.ID.String(),
			Name: ingredient.Name,
		}
	}

	var ingredientUsageModels []*model.IngredientUsage
	for _, usage := range ingredientUsages {
		usageModel := &model.IngredientUsage{
			ID:       usage.ID.String(),
			Quantity: usage.Quantity,
			Unit: &model.Unit{
				Val:    int32(usage.Unit),
				Name:   usage.Unit.String(),
				Symbol: usage.Unit.Symbol(),
			},
			Ingredient: ingredientMap[usage.IngredientID.String()],
		}
		ingredientUsageModels = append(ingredientUsageModels, usageModel)
	}
	return ingredientUsageModels, nil
}

// User is the resolver for the user field.
func (r *recipeResolver) User(ctx context.Context, obj *model.Recipe) (*model.User, error) {
	// Called twice, could eager load user when loading recipe if we
	recipe, err := r.RecipeService.GetRecipeByID(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe for user resolver: %w", err)
	}
	if recipe == nil {
		return nil, fmt.Errorf("recipe not found for user resolver")
	}
	user, err := r.UserService.GetUserByID(ctx, recipe.UserID.String())
	if err != nil {
		return nil, fmt.Errorf("failed to get user for recipe: %w", err)
	}
	if user == nil {
		return nil, fmt.Errorf("user not found for recipe")
	}
	return &model.User{
		ID:    user.ID.String(),
		Email: user.Email,
	}, nil
}

// Source is the resolver for the source field.
func (r *recipeResolver) Source(ctx context.Context, obj *model.Recipe) (*model.RecipeSource, error) {
	recipeSource, err := r.RecipeService.GetRecipeSourceByRecipeID(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe source for recipe: %w", err)
	}
	if recipeSource == nil {
		return &model.RecipeSource{Type: 0}, nil
	}
	return &model.RecipeSource{
		Type:         int32(recipeSource.Type),
		URL:          recipeSource.URL,
		BookTitle:    recipeSource.BookTitle,
		BookPage:     recipeSource.BookPage,
		Instructions: recipeSource.Instructions,
	}, nil
}

// Recipe returns graph.RecipeResolver implementation.
func (r *Resolver) Recipe() graph.RecipeResolver { return &recipeResolver{r} }

type recipeResolver struct{ *Resolver }
