package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"foodplanner/internal/auth"
	"foodplanner/internal/gql/graph"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/logging"
	"foodplanner/internal/recipe"
)

// CreateRecipe is the resolver for the createRecipe field.
func (r *mutationResolver) CreateRecipe(ctx context.Context, input model.CreateRecipeInput) (*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	ingredientUsageRequests := make([]recipe.CreateIngredientUsageRequest, len(input.IngredientUsages))
	for i, usage := range input.IngredientUsages {
		ingredientUsageRequests[i] = recipe.CreateIngredientUsageRequest{
			IngredientID: usage.IngredientID,
			Quantity:     usage.Quantity,
			Unit:         int(usage.Unit),
		}
	}

	recipeSourceRequest := recipe.CreateRecipeSourceRequest{
		Type:         int(input.RecipeSource.Type),
		URL:          input.RecipeSource.URL,
		BookTitle:    input.RecipeSource.BookTitle,
		BookPage:     input.RecipeSource.BookPage,
		Instructions: input.RecipeSource.Instructions,
	}

	request := recipe.CreateRecipeRequest{
		Name:        input.Name,
		Ingredients: ingredientUsageRequests,
		UserID:      claims.UserID,
		PrepMins:    int(input.PrepMins),
		CookMins:    int(input.CookMins),
		Portions:    int(input.Portions),
		Source:      recipeSourceRequest,
	}
	recipeContainer, err := r.RecipeService.CreateRecipe(ctx, request)
	if err != nil {
		logger.Error("Failed to create recipe", "error", err)
		return nil, err
	}
	return mapRecipe(recipeContainer), nil
}

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context) ([]*model.Recipe, error) {
	logger := logging.FromContext(ctx)
	recipes, err := r.RecipeService.GetAllRecipes(ctx)
	if err != nil {
		logger.Error("Failed to get all recipes", "error", err)
		return nil, err
	}

	return mapRecipes(recipes), nil
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id string) (*model.Recipe, error) {
	logger := logging.FromContext(ctx).With("recipe_id", id)
	recipe, err := r.RecipeService.GetRecipeByID(ctx, id)
	if err != nil {
		logger.Error("Failed to get recipe by ID", "error", err)
		return nil, err
	}
	if recipe == nil {
		return nil, nil
	}
	recipeModel := mapRecipe(recipe)
	return recipeModel, nil
}

// Author is the resolver for the author field.
func (r *recipeResolver) Author(ctx context.Context, obj *model.Recipe) (*model.User, error) {
	user, err := r.UserService.GetUserByID(ctx, obj.AuthorID)
	if err != nil {
		return nil, err
	}
	return mapUser(user), nil
}

// CurrentVersion is the resolver for the currentVersion field.
func (r *recipeResolver) CurrentVersion(ctx context.Context, obj *model.Recipe) (*model.RecipeVersion, error) {
	if obj.CurrentVersion != nil {
		return obj.CurrentVersion, nil
	}

	recipeVersion, err := r.RecipeService.GetRecipeVersionByID(ctx, obj.CurrentVersionID)
	if err != nil {
		return nil, err
	}
	if recipeVersion == nil {
		return nil, nil
	}
	return mapRecipeVersion(recipeVersion), nil
}

// Versions is the resolver for the versions field.
func (r *recipeResolver) Versions(ctx context.Context, obj *model.Recipe) ([]*model.RecipeVersion, error) {
	versions, err := r.RecipeService.GetRecipeVersionsByRecipeID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	var result []*model.RecipeVersion
	for _, version := range versions {
		result = append(result, mapRecipeVersion(version))
	}
	return result, nil
}

// Recipe is the resolver for the recipe field.
func (r *recipeVersionResolver) Recipe(ctx context.Context, obj *model.RecipeVersion) (*model.Recipe, error) {
	logger := logging.FromContext(ctx).With("recipe_id", obj.RecipeID)
	if obj.RecipeID == "" {
		logger.Warn("Recipe version has no associated recipe ID", "recipe_version_id", obj.ID)
		return nil, nil
	}
	recipe, err := r.RecipeService.GetRecipeByID(ctx, obj.RecipeID)
	if err != nil {
		logger.Error("Failed to get recipe for recipe version", "error", err)
		return nil, err
	}
	if recipe == nil {
		logger.Warn("No recipe found for recipe version", "recipe_version_id", obj.ID, "recipe_id", obj.RecipeID)
		return nil, nil
	}
	return mapRecipe(recipe), nil
}

// IngredientUsages is the resolver for the ingredientUsages field.
func (r *recipeVersionResolver) IngredientUsages(ctx context.Context, obj *model.RecipeVersion) ([]*model.IngredientUsage, error) {
	logger := logging.FromContext(ctx).With("recipe_id", obj.ID)
	ingredientUsages, err := r.RecipeService.GetIngredientUsagesByRecipeVersionID(ctx, obj.ID)
	if err != nil {
		logger.Error("Failed to get ingredient usages for recipe", "error", err)
		return nil, err
	}
	if ingredientUsages == nil {
		logger.Error("No ingredient usages found for recipe", "recipe_version_id", obj.ID)
		return nil, nil
	}

	ingredientIDs := make([]string, len(ingredientUsages))
	for i, usage := range ingredientUsages {
		ingredientIDs[i] = usage.IngredientID.String()
	}

	// Eagerly load ingredients, separate into data loader later
	ingredients, err := r.IngredientsService.GetIngredientsByIDs(ctx, logger, ingredientIDs)
	if err != nil {
		logger.Error("Failed to get ingredients for ingredient usages", "error", err)
		return nil, err
	}
	ingredientMap := make(map[string]*model.Ingredient)
	for _, ingredient := range ingredients {
		ingredientMap[ingredient.ID.String()] = &model.Ingredient{
			ID:            ingredient.ID.String(),
			Name:          ingredient.Name,
			Counter:       ingredient.Counter,
			Plural:        ingredient.Plural,
			CounterPlural: ingredient.CounterPlural,
		}
	}

	var ingredientUsageModels []*model.IngredientUsage
	for _, usage := range ingredientUsages {
		usageModel := &model.IngredientUsage{
			ID:       usage.ID.String(),
			Quantity: usage.Quantity,
			Unit: &model.Unit{
				Val:    int32(usage.Unit),
				Name:   usage.Unit.String(),
				Symbol: usage.Unit.Symbol(),
			},
			Ingredient: ingredientMap[usage.IngredientID.String()],
		}
		ingredientUsageModels = append(ingredientUsageModels, usageModel)
	}
	return ingredientUsageModels, nil
}

// Source is the resolver for the source field.
func (r *recipeVersionResolver) Source(ctx context.Context, obj *model.RecipeVersion) (*model.RecipeSource, error) {
	recipeSource, err := r.RecipeService.GetRecipeSourceByRecipeVersionID(ctx, obj.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get recipe source for recipe: %w", err)
	}
	if recipeSource == nil {
		return &model.RecipeSource{Type: 0}, nil
	}
	return &model.RecipeSource{
		Type:         int32(recipeSource.Type),
		URL:          recipeSource.URL,
		BookTitle:    recipeSource.BookTitle,
		BookPage:     recipeSource.BookPage,
		Instructions: recipeSource.Instructions,
	}, nil
}

// Recipe returns graph.RecipeResolver implementation.
func (r *Resolver) Recipe() graph.RecipeResolver { return &recipeResolver{r} }

// RecipeVersion returns graph.RecipeVersionResolver implementation.
func (r *Resolver) RecipeVersion() graph.RecipeVersionResolver { return &recipeVersionResolver{r} }

type recipeResolver struct{ *Resolver }
type recipeVersionResolver struct{ *Resolver }
