package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"foodplanner/internal/auth"
	"foodplanner/internal/gql/graph"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/recipe"
)

// CreateRecipe is the resolver for the createRecipe field.
func (r *mutationResolver) CreateRecipe(ctx context.Context, input model.CreateRecipeInput) (*model.Recipe, error) {
	_, err := auth.ClaimsFromContext(ctx)
	if err != nil {
		return nil, err
	}

	ingredientUsageRequests := make([]recipe.CreateIngredientUsageRequest, len(input.IngredientUsages))
	for i, usage := range input.IngredientUsages {
		ingredientUsageRequests[i] = recipe.CreateIngredientUsageRequest{
			IngredientID: usage.IngredientID,
			Quantity:     usage.Quantity,
			Unit:         int(usage.Unit),
		}
	}

	request := recipe.CreateRecipeRequest{
		Name:        input.Name,
		Ingredients: ingredientUsageRequests,
	}
	recipe, err := r.RecipeService.CreateRecipe(ctx, request)
	if err != nil {
		return nil, fmt.Errorf("failed to create recipe: %w", err)
	}
	recipeModel := &model.Recipe{
		ID:   recipe.ID.String(),
		Name: recipe.Name,
	}
	return recipeModel, nil
}

// Recipes is the resolver for the recipes field.
func (r *queryResolver) Recipes(ctx context.Context) ([]*model.Recipe, error) {
	recipes, err := r.RecipeService.GetAllRecipes(ctx)
	if err != nil {
		return nil, err
	}
	var recipeModels []*model.Recipe
	for _, recipe := range recipes {
		recipeModel := model.Recipe{
			ID:   recipe.ID.String(),
			Name: recipe.Name,
		}
		recipeModels = append(recipeModels, &recipeModel)
	}
	return recipeModels, nil
}

// Recipe is the resolver for the recipe field.
func (r *queryResolver) Recipe(ctx context.Context, id string) (*model.Recipe, error) {
	recipe, err := r.RecipeService.GetRecipeByID(ctx, id)
	if err != nil {
		return nil, err
	}
	if recipe == nil {
		return nil, nil
	}
	recipeModel := &model.Recipe{
		ID:   recipe.ID.String(),
		Name: recipe.Name,
	}
	return recipeModel, nil
}

// IngredientUsages is the resolver for the ingredientUsages field.
func (r *recipeResolver) IngredientUsages(ctx context.Context, obj *model.Recipe) ([]*model.IngredientUsage, error) {
	ingredientUsages, err := r.RecipeService.GetIngredientUsagesByRecipeID(ctx, obj.ID)
	if err != nil {
		return nil, err
	}
	var ingredientUsageModels []*model.IngredientUsage
	for _, usage := range ingredientUsages {
		usageModel := &model.IngredientUsage{
			ID:       usage.ID.String(),
			Quantity: usage.Quantity,
			Unit: &model.Unit{
				Val:  int32(usage.Unit),
				Name: usage.Unit.String(),
			},
		}
		ingredientUsageModels = append(ingredientUsageModels, usageModel)
	}
	return ingredientUsageModels, nil
}

// Recipe returns graph.RecipeResolver implementation.
func (r *Resolver) Recipe() graph.RecipeResolver { return &recipeResolver{r} }

type recipeResolver struct{ *Resolver }
