package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"foodplanner/internal/gql/graph/model"
)

// CreateImageUploadURL is the resolver for the createImageUploadUrl field.
func (r *mutationResolver) CreateImageUploadURL(ctx context.Context, input model.CreateImageUploadURLInput) (*model.ImageUploadPayload, error) {
	panic(fmt.Errorf("not implemented: CreateImageUploadURL - createImageUploadUrl"))
}
