package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	grapherrors "foodplanner/internal/gql/graph/errors"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/logging"
	"foodplanner/internal/upload"

	"github.com/google/uuid"
)

// CreateImageUploadURL is the resolver for the createImageUploadUrl field.
func (r *mutationResolver) CreateImageUploadURL(ctx context.Context, input model.CreateImageUploadURLInput) (*model.ImageUploadPayload, error) {
	logger := logging.FromContext(ctx)
	claims, err := RequireAuth(ctx)
	if err != nil {
		logger.Error("Unauthenticated access to CreateImageUploadURL mutation", "error", err)
		return nil, err
	}

	if r.UploadService == nil {
		logger.Error("Upload service is not configured")
		return nil, grapherrors.NewInternalError("upload service is not configured")
	}

	ownerUserID, err := uuid.Parse(claims.UserID)
	if err != nil {
		logger.Error("Invalid user ID in auth claims", "error", err, "claimsUserID", claims.UserID)
		return nil, grapherrors.NewInternalError("invalid user identity")
	}

	request := upload.CreateImageUploadURLRequest{
		OwnerUserID:   ownerUserID,
		FileName:      input.FileName,
		FileType:      input.FileType,
		FileSizeBytes: int64(input.FileSize),
		Purpose:       upload.UploadPurposeRecipeImage,
	}

	result, err := r.UploadService.CreateImageUploadURL(ctx, request)
	if err != nil {
		logger.Error("Failed to create image upload URL", "error", err, "userID", ownerUserID.String())
		return nil, err
	}

	return &model.ImageUploadPayload{
		UploadURL: result.UploadURL,
		FileURL:   result.FileURL,
		UploadID:  result.UploadID.String(),
	}, nil

}
