package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"foodplanner/internal/auth"
	"foodplanner/internal/gql/graph"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/logging"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	logger := logging.FromContext(ctx)
	user, err := r.UserService.GetUserByID(ctx, id)
	if err != nil {
		logger.Error("Failed to get user by ID", "error", err, "userID", id)
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return mapUser(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	logger := logging.FromContext(ctx)
	claims, ok := auth.ClaimsFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("unauthenticated")
	}

	user, err := r.UserService.GetUserByID(ctx, claims.UserID)
	if err != nil {
		logger.Error("Failed to get user by ID", "error", err, "userID", claims.UserID)
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return mapUser(user), nil
}

// Recipes is the resolver for the recipes field.
func (r *userResolver) Recipes(ctx context.Context, obj *model.User) ([]*model.Recipe, error) {
	logger := logging.FromContext(ctx)

	recipes, err := r.RecipeService.GetRecipesByUserID(ctx, obj.ID)
	if err != nil {
		logger.Error("Failed to get active recipes for user", "error", err)
		return nil, err
	}
	return mapRecipes(recipes), nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
