package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"
	"foodplanner/internal/gql/graph"
	"foodplanner/internal/gql/graph/model"
	"foodplanner/internal/logging"
	"foodplanner/internal/recipe"

	"github.com/google/uuid"
)

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	logger := logging.FromContext(ctx)
	user, err := r.UserService.GetUserByID(ctx, uuid.MustParse(id))
	if err != nil {
		logger.Error("Failed to get user by ID", "error", err, "userID", id)
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return mapUser(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	logger := logging.FromContext(ctx)
	claims, err := RequireAuth(ctx)
	if err != nil {
		logger.Error("Unauthenticated access to Me query", "error", err)
		return nil, err
	}

	user, err := r.UserService.GetUserByID(ctx, uuid.MustParse(claims.UserID))
	if err != nil {
		logger.Error("Failed to get user by ID", "error", err, "userID", claims.UserID)
		return nil, err
	}
	if user == nil {
		return nil, nil
	}
	return mapUser(user), nil
}

// Recipes is the resolver for the recipes field.
func (r *userResolver) Recipes(ctx context.Context, obj *model.User, pagination *model.PaginationInput, filter *model.RecipeFilterInput) (*model.RecipeConnection, error) {
	logger := logging.FromContext(ctx)
	first := 20
	var after *string
	if pagination != nil {
		if pagination.First != nil {
			first = int(*pagination.First)
		}
		after = pagination.After
	}

	var filterModel *model.RecipeFilterInput
	if filter != nil {
		filterModel = filter
	} else {
		filterModel = &model.RecipeFilterInput{
			UserID: &obj.ID,
		}
	}

	var userID *uuid.UUID
	if filterModel.UserID != nil {
		parsed, err := uuid.Parse(*filterModel.UserID)
		if err != nil {
			logger.Error("Invalid userID in recipe filter", "error", err, "userID", *filterModel.UserID)
			return nil, fmt.Errorf("invalid userID in recipe filter: %w", err)
		}
		userID = &parsed
	}
	params := recipe.RecipeListParams{
		Pagination: recipe.RecipePagination{
			First: first,
			After: after,
		},
		Filter: recipe.RecipeFilter{
			Query:  filterModel.Query,
			UserID: userID,
		},
	}

	recipes, endCursor, err := r.RecipeService.GetRecipes(ctx, params)
	if err != nil {
		logger.Error("Failed to get all recipes", "error", err)
		return nil, err
	}

	if recipes == nil {
		return &model.RecipeConnection{
			Edges:    []*model.RecipeEdge{},
			PageInfo: &model.PageInfo{HasNextPage: false, EndCursor: nil},
		}, nil
	}

	connection := &model.RecipeConnection{
		Edges:    make([]*model.RecipeEdge, len(recipes)),
		PageInfo: &model.PageInfo{HasNextPage: endCursor != nil, EndCursor: endCursor},
	}
	for i, recipeWithCursor := range recipes {
		if recipeWithCursor == nil || recipeWithCursor.Recipe == nil {
			logger.Error("Recipe service returned invalid recipe page item")
			return nil, fmt.Errorf("recipe service returned invalid recipe page item")
		}
		connection.Edges[i] = &model.RecipeEdge{
			Cursor: recipeWithCursor.Cursor,
			Node:   mapRecipe(recipeWithCursor.Recipe),
		}
	}
	return connection, nil
}

// User returns graph.UserResolver implementation.
func (r *Resolver) User() graph.UserResolver { return &userResolver{r} }

type userResolver struct{ *Resolver }
