// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Jwt  string `json:"jwt"`
	User *User  `json:"user"`
}

type Mutation struct {
}

type NewRecipe struct {
	Name string `json:"name"`
}

type Query struct {
}

type Recipe struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID    string `json:"id"`
	Email string `json:"email"`
}
