// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AuthPayload struct {
	Jwt  string `json:"jwt"`
	User *User  `json:"user"`
}

type CreateIngredientUsageInput struct {
	IngredientID string  `json:"ingredientID"`
	Unit         int32   `json:"unit"`
	Quantity     float64 `json:"quantity"`
}

type CreateRecipeInput struct {
	Name             string                        `json:"name"`
	IngredientUsages []*CreateIngredientUsageInput `json:"ingredientUsages"`
	PrepMins         int32                         `json:"prepMins"`
	CookMins         int32                         `json:"cookMins"`
	Portions         int32                         `json:"portions"`
	RecipeSource     *CreateRecipeSourceInput      `json:"recipeSource"`
}

type CreateRecipeSourceInput struct {
	Type         int32   `json:"type"`
	URL          *string `json:"url,omitempty"`
	BookTitle    *string `json:"bookTitle,omitempty"`
	BookPage     *int32  `json:"bookPage,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
}

type DeleteRecipeInput struct {
	ID string `json:"id"`
}

type Ingredient struct {
	ID            string  `json:"id"`
	Name          string  `json:"name"`
	PreferredUnit *Unit   `json:"preferredUnit"`
	Counter       *string `json:"counter,omitempty"`
	Plural        *string `json:"plural,omitempty"`
	CounterPlural *string `json:"counterPlural,omitempty"`
}

type IngredientUsage struct {
	ID         string      `json:"id"`
	Ingredient *Ingredient `json:"ingredient"`
	Unit       *Unit       `json:"unit"`
	Quantity   float64     `json:"quantity"`
}

type Mutation struct {
}

type Query struct {
}

type Recipe struct {
	ID               string             `json:"id"`
	Name             string             `json:"name"`
	IngredientUsages []*IngredientUsage `json:"ingredientUsages"`
	User             *User              `json:"user"`
	PrepMins         int32              `json:"prepMins"`
	CookMins         int32              `json:"cookMins"`
	Portions         int32              `json:"portions"`
	Source           *RecipeSource      `json:"source"`
}

type RecipeFilter struct {
	Status *RecipeStatus `json:"status,omitempty"`
}

type RecipeSource struct {
	Type         int32   `json:"type"`
	URL          *string `json:"url,omitempty"`
	BookTitle    *string `json:"bookTitle,omitempty"`
	BookPage     *int32  `json:"bookPage,omitempty"`
	Instructions *string `json:"instructions,omitempty"`
}

type SignInInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SignUpInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Username string `json:"username"`
}

type UndeleteRecipeInput struct {
	ID string `json:"id"`
}

type Unit struct {
	Val    int32  `json:"val"`
	Name   string `json:"name"`
	Symbol string `json:"symbol"`
}

type User struct {
	ID       string    `json:"id"`
	Email    string    `json:"email"`
	Username string    `json:"username"`
	Recipes  []*Recipe `json:"recipes"`
}

type RecipeStatus string

const (
	RecipeStatusActive  RecipeStatus = "ACTIVE"
	RecipeStatusDeleted RecipeStatus = "DELETED"
)

var AllRecipeStatus = []RecipeStatus{
	RecipeStatusActive,
	RecipeStatusDeleted,
}

func (e RecipeStatus) IsValid() bool {
	switch e {
	case RecipeStatusActive, RecipeStatusDeleted:
		return true
	}
	return false
}

func (e RecipeStatus) String() string {
	return string(e)
}

func (e *RecipeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecipeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecipeStatus", str)
	}
	return nil
}

func (e RecipeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecipeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecipeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
